spring:
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:mariadb://localhost:3306/bookrent
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
      show-sql: true
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: password